
#主配置
node:
    #节点名称
    name: sys_main
    #访问端口
    port: 80
    #路径替换
    replace:
        /static: ./webapp/view/static
        /stay: ./webapp/upload
        
    #转发映射
    forward:
        /index: ./webapp/view/home.html
        /admin/login: ./webapp/view/backstage/login.html
        /admin/((\w|-){2,20}): ./webapp/view/backstage/index.html
        /admin-page/((\w|-){2,20}): ./webapp/view/backstage/page/{$1}.html
        
    #重定向跳转
    redirect:
        /: /index
        /admin: /admin/console
        
    #权限拦截
    intercept:
        /admin(.+?):
            permit: manager,supermanager
            redirect: /admin/login
            ignore:
                - /admin/login
    
    #自定义扫描路径
    #controller:
    #    - ./webapp/cons
    #service:
    #    - ./webapp/sers
    
    #静态文件缓存时间
    staticCacheTime: 0
    
    #作为服务中心
    #center: true
    
    #作为消费者
    #client: 
    #    type: http
    #    center: http://localhost:8888

    session: 
        #redis: test
        time: 30
        refresh: 2
        
    404: 
        url: /404.html
        path: ./webapp/view/404.html

    #固化第三方请求get
    #get:
    #    /weather_api: http://t.weather.sojson.com/api/weather/city/101030100
    
#数据库     
db:
    #test: 
    #    type: mysql
    #    host: 
    #    user: 
    #    password: 
    #    database: 
    #    dateStrings: true
        
    #test2:
    #    type: mongodb
    #    host: localhost
    #    db: test2

#redis缓存  
#redis:
#    test:
#        host: localhost
#        port: 6379